### ISSUE TITLE
数据库要如何设置？

### ISSUE THREAD

**Issue by xermao** [nusr/comic#5]
我这一搜索漫画服务器端就报错

[Node] Error: ER_BAD_DB_ERROR: Unknown database 'comic'
[Node]     at Handshake.Sequence._packetToError (H:\Source\ComicHub\server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
[Node]     at Handshake.ErrorPacket (H:\Source\ComicHub\server\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
[Node]     at Protocol._parsePacket (H:\Source\ComicHub\server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
[Node]     at Parser._parsePacket (H:\Source\ComicHub\server\node_modules\mysql\lib\protocol\Parser.js:433:10)
[Node]     at Parser.write (H:\Source\ComicHub\server\node_modules\mysql\lib\protocol\Parser.js:43:10)
[Node]     at Protocol.write (H:\Source\ComicHub\server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
[Node]     at Socket.<anonymous> (H:\Source\ComicHub\server\node_modules\mysql\lib\Connection.js:91:28)
[Node]     at Socket.<anonymous> (H:\Source\ComicHub\server\node_modules\mysql\lib\Connection.js:525:10)
[Node]     at Socket.emit (events.js:182:13)
[Node]     at addChunk (_stream_readable.js:283:12)

**Comment by nusr** [comment]
https://github.com/nusr/ComicHub/blob/master/docs/joinUs.md#%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BD%BF%E7%94%A8
